CREATE DATABASE IF NOT EXISTS piq_db;
USE piq_db;

CREATE TABLE IF NOT EXISTS sites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  css_selector TEXT NOT NULL,
  last_hash VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  site_id INT NOT NULL,
  captured_html TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;

ALTER TABLE sites ADD COLUMN IF NOT EXISTS is_frozen BOOLEAN DEFAULT FALSE;

ALTER TABLE sites ADD COLUMN IF NOT EXISTS user_id INT NOT NULL;
ALTER TABLE sites ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE sites 
ADD COLUMN check_interval_minutes INT DEFAULT 60,
ADD COLUMN last_checked DATETIME DEFAULT NULL;

ALTER TABLE alerts MODIFY COLUMN captured_html MEDIUMTEXT;
ALTER TABLE sites ADD COLUMN check_interval_seconds INT DEFAULT 600;
ALTER TABLE sites ADD COLUMN status VARCHAR(20) DEFAULT 'active';
ALTER TABLE sites ADD COLUMN consecutive_errors INT DEFAULT 0;

ALTER TABLE sites ADD COLUMN last_error VARCHAR(255) DEFAULT NULL;
